name: VPN Server (WireGuard)
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
    - name: Install WireGuard
      run: |
        sudo apt update
        sudo apt install -y wireguard
    - name: Setup VPN
      run: |
        # تولید کلیدهای WireGuard
        cd /etc/wireguard
        umask 077
        wg genkey | tee server.key | wg pubkey > server.pub
        wg genkey | tee client.key | wg pubkey > client.pub
        
        # تنظیمات سرور
        sudo bash -c 'cat > wg0.conf << EOF
[Interface]
PrivateKey = $(cat server.key)
Address = 10.0.0.1/24
ListenPort = 51820
PostUp = iptables -A FORWARD -i wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
PostDown = iptables -D FORWARD -i wg0 -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE

[Peer]
PublicKey = $(cat client.pub)
AllowedIPs = 10.0.0.2/32
EOF'
        
        sudo systemctl start wg-quick@wg0
        
        # ساخت کانفیگ کلاینت
        CLIENT_CONFIG="[Interface]\nPrivateKey = $(cat client.key)\nAddress = 10.0.0.2/24\nDNS = 1.1.1.1\n\n[Peer]\nPublicKey = $(cat server.pub)\nEndpoint = $(curl -s ifconfig.me):51820\nAllowedIPs = 0.0.0.0/0\nPersistentKeepalive = 25"
        
        echo -e $CLIENT_CONFIG > /tmp/client.conf
    - name: Upload Config
      uses: actions/upload-artifact@v4
      with:
        name: wireguard-config
        path: /tmp/client.conf
